### ISSUE TITLE
MooTools 1.3

### ISSUE THREAD

**Issue by eerne** [APE-Project/APE_JSF#4]
I get "item.$family is not a function" if I try to run my project with 1.3 compat.

Has anyone yet started to port APE_JSF to MooTools 1.3 ?

**Comment by eerne** [comment]
There was a conflict due to me using 1.3 in the page, but still using 1.2 in the iframe. Replaced mootools-core with 1.3 compat, and everything just works nicely so far.

http://github.com/eerne/APE_JSF/commits/1.3wip

**Comment by eerne** [comment]
Hi this is a bit a weird request, but please do _not_ update APE_JSF work with 1.3-only as it already works with 1.3-compat, but it would be great if we could use APE_JSF with 1.2.x for a while.

There are currently some environments where MooTools core doesn't fully work. See Moo1.3 on Titanium APP issue: 
https://mootools.lighthouseapp.com/projects/2706/tickets/1096-mootools-13-on-titanium-app

https://appcelerator.lighthouseapp.com/projects/32239-titanium-developer/tickets/85-mootools-13-on-titanium-app
